/* Product Adoption Analysis */

SELECT
    p.product_name,
    COUNT(DISTINCT t.customer_id) AS total_customers
FROM transactions t
JOIN products p
ON t.product_id = p.product_id
WHERE t.status = 'Success'
GROUP BY p.product_name
ORDER BY total_customers DESC;

/* Total Revenue Generated by each product*/
SELECT
    p.product_name,
    ROUND(SUM(t.revenue),2) AS total_revenue
FROM transactions t
JOIN products p
ON t.product_id = p.product_id
WHERE t.status='Success'
GROUP BY p.product_name
ORDER BY total_revenue DESC;

/*Product Profitability Ranking*/

SELECT
    p.product_name,

    COUNT(t.transaction_id) AS transactions,

    COUNT(DISTINCT t.customer_id) AS customers,

    ROUND(SUM(t.revenue),2) AS revenue

FROM transactions t

JOIN products p
ON t.product_id=p.product_id

WHERE t.status='Success'

GROUP BY p.product_name

ORDER BY revenue DESC;

/*Revenue Contribution Percentage*/

SELECT

p.product_name,

ROUND(
SUM(t.revenue) *100 /
(SELECT SUM(revenue)
 FROM transactions
 WHERE status='Success'),
2
) AS revenue_percentage


FROM transactions t

JOIN products p
ON t.product_id=p.product_id

WHERE t.status='Success'

GROUP BY p.product_name

ORDER BY revenue_percentage DESC;

/* Revenue by partner*/

SELECT

p.partner_name,

ROUND(SUM(t.revenue),2)
AS partner_revenue


FROM transactions t

JOIN partners p

ON t.partner_id=p.partner_id


WHERE t.status='Success'


GROUP BY p.partner_name


ORDER BY partner_revenue DESC;

/* Partner performance ranking*/

SELECT

partner_name,

revenue,

RANK() OVER(
ORDER BY revenue DESC
)
AS revenue_rank


FROM
(
SELECT

p.partner_name,

SUM(t.revenue) revenue


FROM transactions t

JOIN partners p

ON t.partner_id=p.partner_id

WHERE t.status='Success'

GROUP BY p.partner_name

) x;

/* Customer lifetime value
CLTV = Total Revenue Generated by Customer */

/* Avearge Revenue Per Customer*/

SELECT

customer_id,

ROUND(SUM(revenue),2)
AS customer_lifetime_value


FROM transactions

WHERE status='Success'


GROUP BY customer_id


ORDER BY customer_lifetime_value DESC

LIMIT 20;

SELECT

ROUND(
SUM(revenue) /
COUNT(DISTINCT customer_id),
2
)
AS average_customer_value


FROM transactions

WHERE status='Success';

/* Repeat Usage Analysis*/

SELECT

is_repeat,

COUNT(transaction_id)
AS transactions,

ROUND(SUM(revenue),2)
AS revenue


FROM transactions

WHERE status='Success'


GROUP BY is_repeat;
/* Cross sell success rate*/
SELECT

cross_sell,

COUNT(DISTINCT customer_id)
AS customers


FROM transactions


WHERE status='Success'


GROUP BY cross_sell;

/* Customers using multiple products*/

SELECT

customer_id,

COUNT(DISTINCT product_id)
AS products_used


FROM transactions


WHERE status='Success'


GROUP BY customer_id


HAVING products_used > 1


ORDER BY products_used DESC;

/* Monthly revenue trend*/
SELECT

MONTH(transaction_date)
AS month,

ROUND(SUM(revenue),2)
AS revenue


FROM transactions


WHERE status='Success'


GROUP BY MONTH(transaction_date)


ORDER BY month;

/* Transaction success rate*/

SELECT

status,

COUNT(*) AS transactions,


ROUND(
COUNT(*)*100/
(SELECT COUNT(*) FROM transactions),
2
)
AS percentage


FROM transactions


GROUP BY status;

/* Revenue by customer segment*/

SELECT

c.income_segment,

ROUND(SUM(t.revenue),2)
AS revenue


FROM transactions t


JOIN customers c

ON t.customer_id=c.customer_id


WHERE t.status='Success'


GROUP BY c.income_segment


ORDER BY revenue DESC;

/*Acquisition channel performance*/

SELECT

c.acquisition_channel,


COUNT(DISTINCT c.customer_id)
customers,


ROUND(SUM(t.revenue),2)
revenue


FROM customers c


JOIN transactions t

ON c.customer_id=t.customer_id


WHERE t.status='Success'


GROUP BY c.acquisition_channel


ORDER BY revenue DESC;

/*Overall funnel performance*/

SELECT

stage,

COUNT(DISTINCT customer_id) AS customers

FROM funnel_events

GROUP BY stage

ORDER BY
CASE stage

WHEN 'Viewed' THEN 1
WHEN 'Application Started' THEN 2
WHEN 'KYC Completed' THEN 3
WHEN 'Approved' THEN 4
WHEN 'Activated' THEN 5
WHEN 'First Transaction' THEN 6

END;

/* Funnel conversion rate*/

WITH funnel AS (

SELECT

stage,

COUNT(DISTINCT customer_id) customers

FROM funnel_events

GROUP BY stage

)

SELECT

stage,

customers,

ROUND(
customers *100 /
MAX(customers) OVER(),
2
)
AS conversion_rate_percentage


FROM funnel;

/* Stage wise drop off analysis*/

WITH funnel AS (

SELECT

stage,

COUNT(DISTINCT customer_id) customers

FROM funnel_events

GROUP BY stage

)

SELECT

stage,

customers,

customers -
LEAD(customers) OVER(
ORDER BY
CASE stage

WHEN 'Viewed' THEN 1
WHEN 'Application Started' THEN 2
WHEN 'KYC Completed' THEN 3
WHEN 'Approved' THEN 4
WHEN 'Activated' THEN 5
WHEN 'First Transaction' THEN 6

END
)

AS drop_off_users


FROM funnel;

/* Find biggest drop off stage*/

WITH funnel AS (

SELECT

stage,

COUNT(DISTINCT customer_id) customers

FROM funnel_events

GROUP BY stage

),

dropoffs AS (

SELECT

stage,

customers -
LEAD(customers) OVER(
ORDER BY customers DESC
)

loss

FROM funnel

)

SELECT *

FROM dropoffs

ORDER BY loss DESC

LIMIT 1;

/* Product wise funnel conversion*/

SELECT

p.product_name,

COUNT(
DISTINCT CASE 
WHEN stage='Viewed'
THEN customer_id END
)
AS views,


COUNT(
DISTINCT CASE 
WHEN stage='First Transaction'
THEN customer_id END
)
AS conversions,


ROUND(

COUNT(
DISTINCT CASE 
WHEN stage='First Transaction'
THEN customer_id END
)

*

100

/

COUNT(
DISTINCT CASE 
WHEN stage='Viewed'
THEN customer_id END
),

2)

AS conversion_rate


FROM funnel_events f

JOIN products p

ON f.product_id=p.product_id


GROUP BY p.product_name

ORDER BY conversion_rate DESC;

/* Partner funnel prformance*/

SELECT

p.partner_name,

COUNT(
DISTINCT t.customer_id
)
AS activated_users,


COUNT(
DISTINCT f.customer_id
)
AS funnel_users,


ROUND(

COUNT(DISTINCT t.customer_id)*100/

COUNT(DISTINCT f.customer_id),

2)

AS activation_rate


FROM funnel_events f

JOIN transactions t

ON f.customer_id=t.customer_id

JOIN partners p

ON t.partner_id=p.partner_id


WHERE t.status='Success'


GROUP BY p.partner_name


ORDER BY activation_rate DESC;

/* Monthly funnel trend*/

SELECT

MONTH(event_date) month,

stage,

COUNT(DISTINCT customer_id)
customers


FROM funnel_events


GROUP BY

MONTH(event_date),

stage


ORDER BY month;
/*Customer First Transaction Month */

WITH customer_first_purchase AS (

SELECT

customer_id,

MIN(transaction_date) AS first_purchase_date

FROM transactions

WHERE status='Success'

GROUP BY customer_id

)

SELECT *

FROM customer_first_purchase;

/* Create customer cohort */

WITH customer_cohort AS (

SELECT

customer_id,

DATE_FORMAT(
MIN(transaction_date),
'%Y-%m'
)
AS cohort_month


FROM transactions

WHERE status='Success'


GROUP BY customer_id

)

SELECT *

FROM customer_cohort;

/* Monthly retention */

WITH cohort AS (

SELECT

customer_id,

DATE_FORMAT(
MIN(transaction_date),
'%Y-%m'
)
AS cohort_month


FROM transactions

WHERE status='Success'

GROUP BY customer_id

),

activity AS (

SELECT

customer_id,

DATE_FORMAT(
transaction_date,
'%Y-%m'
)
AS activity_month


FROM transactions

WHERE status='Success'


GROUP BY customer_id,
activity_month

)


SELECT

c.cohort_month,

a.activity_month,

COUNT(DISTINCT a.customer_id)
AS active_customers


FROM cohort c

JOIN activity a

ON c.customer_id=a.customer_id


GROUP BY

c.cohort_month,

a.activity_month;

/* RFM Customer segmentation 
| Metric    | Meaning                             |
| --------- | ----------------------------------- |
| Recency   | How recently customer used product  |
| Frequency | How often customer uses product     |
| Monetary  | How much revenue customer generated | */

/* RFM Metrics */

SELECT

customer_id,


DATEDIFF(
CURRENT_DATE,
MAX(transaction_date)
)
AS recency_days,


COUNT(transaction_id)
AS frequency,


ROUND(
SUM(revenue),
2
)
AS monetary_value


FROM transactions


WHERE status='Success'


GROUP BY customer_id;

/* Assign customer scores */

WITH rfm AS (

SELECT

customer_id,


DATEDIFF(
CURRENT_DATE,
MAX(transaction_date)
)
AS recency,


COUNT(transaction_id)
AS frequency,


SUM(revenue)
AS monetary


FROM transactions


WHERE status='Success'


GROUP BY customer_id

)


SELECT

customer_id,


NTILE(5) OVER(
ORDER BY recency DESC
)
AS recency_score,


NTILE(5) OVER(
ORDER BY frequency
)
AS frequency_score,


NTILE(5) OVER(
ORDER BY monetary
)
AS monetary_score


FROM rfm;

/* Customer segmentation 
Creating segments */

WITH rfm AS (

SELECT

customer_id,


DATEDIFF(
CURRENT_DATE,
MAX(transaction_date)
)
AS recency,


COUNT(transaction_id)
AS frequency,


SUM(revenue)
AS monetary


FROM transactions


WHERE status='Success'


GROUP BY customer_id

)


SELECT

customer_id,


CASE

WHEN recency <30
AND frequency >=10
AND monetary >500

THEN 'VIP Customer'


WHEN recency <60
AND frequency >=5

THEN 'Loyal Customer'


WHEN recency >120

THEN 'At Risk'


ELSE 'Regular Customer'


END AS customer_segment


FROM rfm;

/* Partner profitability analysis */
/* 1. Partner revenue performance */

SELECT

p.partner_name,

COUNT(t.transaction_id) AS total_transactions,

COUNT(DISTINCT t.customer_id) AS unique_customers,

ROUND(SUM(t.revenue),2) AS total_revenue


FROM transactions t


JOIN partners p

ON t.partner_id = p.partner_id


WHERE t.status='Success'


GROUP BY p.partner_name


ORDER BY total_revenue DESC;

/* 2. partner customer lifetime value 
Partner CLTV =
Total Revenue / Number of Customers */

SELECT

p.partner_name,

COUNT(DISTINCT t.customer_id) AS customers,


ROUND(
SUM(t.revenue) /
COUNT(DISTINCT t.customer_id),
2
)
AS avg_customer_value


FROM transactions t


JOIN partners p

ON t.partner_id=p.partner_id


WHERE t.status='Success'


GROUP BY p.partner_name


ORDER BY avg_customer_value DESC;

/* Partner repeat usage rate */

SELECT

p.partner_name,


ROUND(

SUM(
CASE
WHEN t.is_repeat='Yes'
THEN 1
ELSE 0
END
)

*

100

/

COUNT(t.transaction_id),

2

)

AS repeat_usage_percentage


FROM transactions t


JOIN partners p

ON t.partner_id=p.partner_id


WHERE t.status='Success'


GROUP BY p.partner_name


ORDER BY repeat_usage_percentage DESC;

/* Partner cross sell success */

SELECT

p.partner_name,


COUNT(
CASE
WHEN cross_sell='Yes'
THEN 1
END
)

AS cross_sell_users,


ROUND(

COUNT(
CASE
WHEN cross_sell='Yes'
THEN 1
END
)

*

100 /

COUNT(*),

2

)

AS cross_sell_rate


FROM transactions t


JOIN partners p

ON t.partner_id=p.partner_id


WHERE t.status='Success'


GROUP BY p.partner_name


ORDER BY cross_sell_rate DESC;

/* Partner profitability score */

WITH partner_metrics AS

(

SELECT


p.partner_name,


SUM(t.revenue) AS revenue,


AVG(
CASE
WHEN t.is_repeat='Yes'
THEN 1
ELSE 0
END
) AS repeat_rate,


AVG(
CASE
WHEN t.cross_sell='Yes'
THEN 1
ELSE 0
END
) AS cross_sell_rate,


COUNT(DISTINCT t.customer_id)
AS customers


FROM transactions t


JOIN partners p

ON t.partner_id=p.partner_id


WHERE t.status='Success'


GROUP BY p.partner_name

)


SELECT


partner_name,


ROUND(

(revenue/1000)

+

(repeat_rate*100)

+

(cross_sell_rate*100)

+

(customers/10),

2

)

AS profitability_score


FROM partner_metrics


ORDER BY profitability_score DESC;

/* Product recommendation analysis */
/* 1. Product Pair analysis */

SELECT

t1.product_id AS product_1,

t2.product_id AS product_2,


COUNT(DISTINCT t1.customer_id)
AS customers


FROM transactions t1


JOIN transactions t2


ON t1.customer_id=t2.customer_id


AND t1.product_id <> t2.product_id



WHERE t1.status='Success'

AND t2.status='Success'


GROUP BY

t1.product_id,

t2.product_id


ORDER BY customers DESC;

/*2.Customer product adoption matrix */

SELECT

customer_id,


GROUP_CONCAT(
DISTINCT product_id
)

AS products_used


FROM transactions


WHERE status='Success'


GROUP BY customer_id;

/* 3.identify cross sell opportunities */

SELECT

customer_id,

COUNT(DISTINCT product_id)
AS products_used


FROM transactions


WHERE status='Success'


GROUP BY customer_id


HAVING products_used = 1;

/* Product revenue + adoption ranking */

SELECT

p.product_name,


COUNT(DISTINCT t.customer_id)
AS users,


COUNT(t.transaction_id)
AS transactions,


ROUND(SUM(t.revenue),2)
AS revenue,


ROUND(

SUM(t.revenue) /

COUNT(DISTINCT t.customer_id),

2

)

AS revenue_per_customer


FROM transactions t


JOIN products p

ON t.product_id=p.product_id


WHERE t.status='Success'


GROUP BY p.product_name


ORDER BY revenue DESC;
